//
//  DeveloperPreview.swift
//  ab&b
//
//  Created by Rayan Karim checa on 7/17/24.
//
/*
import Foundation

class DeveloperPreview
{
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 8,
              numberOfBeds: 4,
              latitude: -80.1936,
              longitude: 25.7850,
              address: "main street",
              city: "Miami",
              state: "Florida",
              title: "Miami villa",
              type: .villa,
              imageURLs: ["listing-1","listing-2","listing-3", "listing-4"],
              rating: 4.9,
              pricePerNight: 567,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 50
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Adam West",
              ownerImageUrl: "profile-2",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              latitude: -67.1936,
              longitude: 11.7850,
              address: "main2 street",
              city: "Aspen",
              state: "Colorado",
              title: "Aspen town house",
              type: .townhouse,
              imageURLs: ["listing-5","listing-6","listing-7", "listing-8"],
              rating: 4.9,
              pricePerNight: 800,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 29
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "East South",
              ownerImageUrl: "profile-3",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              latitude: -37.1936,
              longitude: 21.7850,
              address: "maiiin street",
              city: "melanie",
              state: "rayan",
              title: "melanie bootiful",
              type: .townhouse,
              imageURLs: ["listing-9","listing-10","listing-11", "listing-12"],
              rating: 4.9,
              pricePerNight: 800,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 483
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Adam West",
              ownerImageUrl: "profile-4",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              latitude: -67.1936,
              longitude: 11.7850,
              address: "main2 street",
              city: "Aspen",
              state: "Colorado",
              title: "Aspen town house",
              type: .townhouse,
              imageURLs: ["listing-13","listing-14","listing-15", "listing-16"],
              rating: 4.9,
              pricePerNight: 800,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 29
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "James May",
              ownerImageUrl: "profile-5",
              numberOfBedrooms: 2,
              numberOfBathrooms: 1,
              numberOfGuests: 4,
              numberOfBeds: 2,
              latitude: -67.1936,
              longitude: 11.7850,
              address: "387 W Center St, Richfield, UT 84701, USA",
              city: "Richfield",
              state: "Utah",
              title: "Curated abode w/ close proximity to National Parks",
              type: .house,
              imageURLs: ["listing-17","listing-18","listing-19", "listing-20"],
              rating: 4.95,
              pricePerNight: 119,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .office, .kitchen],
              reviews: 177
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Adam West",
              ownerImageUrl: "profile-6",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              latitude: -67.1936,
              longitude: 11.7850,
              address: "main2 street",
              city: "Aspen",
              state: "Colorado",
              title: "Aspen town house",
              type: .apartment,
              imageURLs: ["listing-21","listing-22","listing-23", "listing-24"],
              rating: 4.9,
              pricePerNight: 800,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 29
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Adam West",
              ownerImageUrl: "profile-7",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              latitude: -67.1936,
              longitude: 11.7850,
              address: "main2 street",
              city: "Aspen",
              state: "Colorado",
              title: "Aspen town house",
              type: .townhouse,
              imageURLs: ["listing-25","listing-26","listing-27", "listing-28"],
              rating: 4.9,
              pricePerNight: 800,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 29
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Adam West",
              ownerImageUrl: "profile-8",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              latitude: -67.1936,
              longitude: 11.7850,
              address: "main2 street",
              city: "Aspen",
              state: "Colorado",
              title: "Aspen town house",
              type: .townhouse,
              imageURLs: ["listing-29","listing-30","listing-31", "listing-32"],
              rating: 4.9,
              pricePerNight: 800,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 29
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Adam West",
              ownerImageUrl: "profile-9",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              latitude: -67.1936,
              longitude: 11.7850,
              address: "main2 street",
              city: "Aspen",
              state: "Colorado",
              title: "Aspen town house",
              type: .townhouse,
              imageURLs: ["listing-33","listing-34","listing-35", "listing-36"],
              rating: 4.9,
              pricePerNight: 800,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 29
        ),
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "North borth",
              ownerImageUrl: "profile-10",
              numberOfBedrooms: 2,
              numberOfBathrooms: 1,
              numberOfGuests: 6,
              numberOfBeds: 9,
              latitude: -30.1936,
              longitude: 11.7850,
              address: "elmore street",
              city: "Los Angeles",
              state: "California",
              title: "melanie bootiful",
              type: .townhouse,
              imageURLs: ["listing-37","listing-38","listing-39", "listing-40"],
              rating: 4.9,
              pricePerNight: 80,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              reviews: 882
        )
    ]
}
*/


//
//  DeveloperPreview.swift
//  ab&b
//
//  Created by Rayan Karim checa on 7/17/24.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()

    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "male-profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 8,
            numberOfBeds: 4,
            latitude: 34.0522,
            longitude: -118.2437,
            address: "123 Main St",
            city: "Los Angeles",
            state: "California",
            title: "Luxurious Villa in Los Angeles",
            type: .villa,
            imageURLs: ["listing-1", "listing-2", "listing-3", "listing-4"],
            rating: 4.9,
            pricePerNight: 567,
            features: [.selfCheckin, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony],
            reviews: 50
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Adam West",
            ownerImageUrl: "profile-2",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            latitude: 39.1911,
            longitude: -106.8175,
            address: "456 Aspen St",
            city: "Aspen",
            state: "Colorado",
            title: "Charming Townhouse in Aspen",
            type: .townhouse,
            imageURLs: ["listing-5", "listing-6", "listing-7", "listing-8"],
            rating: 4.9,
            pricePerNight: 800,
            features: [.greatLocation, .greatForRemoteWork],
            amenities: [.wifi, .office, .airConditioning],
            reviews: 29
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "East South",
            ownerImageUrl: "profile-3",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            latitude: 40.7128,
            longitude: -74.0060,
            address: "789 Broadway",
            city: "New York",
            state: "New York",
            title: "Stylish Loft in New York",
            type: .loft,
            imageURLs: ["listing-9", "listing-10", "listing-11", "listing-12"],
            rating: 4.9,
            pricePerNight: 1200,
            features: [.greatCheckinExperience, .superHost],
            amenities: [.wifi, .gym, .soundSystem],
            reviews: 483
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "James May",
            ownerImageUrl: "profile-4",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 4,
            numberOfBeds: 2,
            latitude: 37.7749,
            longitude: -122.4194,
            address: "1010 Lombard St",
            city: "San Francisco",
            state: "California",
            title: "Cozy Apartment in San Francisco",
            type: .apartment,
            imageURLs: ["listing-13", "listing-14", "listing-15", "listing-16"],
            rating: 4.8,
            pricePerNight: 350,
            features: [.greatLocation, .top10PercentOfHomes],
            amenities: [.wifi, .kitchen, .laundry],
            reviews: 77
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Adam West",
            ownerImageUrl: "profile-5",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            latitude: 25.7617,
            longitude: -80.1918,
            address: "2020 Ocean Dr",
            city: "Miami",
            state: "Florida",
            title: "Beachfront House in Miami",
            type: .house,
            imageURLs: ["listing-17", "listing-18", "listing-19", "listing-20"],
            rating: 4.95,
            pricePerNight: 900,
            features: [.superHost, .greatCheckinExperience],
            amenities: [.wifi, .alarmSystem, .pool],
            reviews: 177
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "profile-6",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 3,
            latitude: 36.1699,
            longitude: -115.1398,
            address: "3030 Vegas Blvd",
            city: "Las Vegas",
            state: "Nevada",
            title: "Modern Suite in Las Vegas",
            type: .suite,
            imageURLs: ["listing-21", "listing-22", "listing-23", "listing-24"],
            rating: 4.7,
            pricePerNight: 400,
            features: [.greatLocation, .greatForRemoteWork],
            amenities: [.wifi, .office, .tv],
            reviews: 35
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Emily Clark",
            ownerImageUrl: "profile-7",
            numberOfBedrooms: 5,
            numberOfBathrooms: 4,
            numberOfGuests: 10,
            numberOfBeds: 5,
            latitude: 51.5074,
            longitude: -0.1278,
            address: "404 London St",
            city: "London",
            state: "England",
            title: "Elegant Townhouse in London",
            type: .townhouse,
            imageURLs: ["listing-25", "listing-26", "listing-27", "listing-28"],
            rating: 5.0,
            pricePerNight: 1500,
            features: [.top10PercentOfHomes, .greatCheckinExperience],
            amenities: [.wifi, .kitchen, .garage],
            reviews: 50
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Michael Johnson",
            ownerImageUrl: "profile-8",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 8,
            numberOfBeds: 4,
            latitude: 34.0522,
            longitude: -118.2437,
            address: "505 Sunset Blvd",
            city: "Los Angeles",
            state: "California",
            title: "Spacious Apartment in Los Angeles",
            type: .apartment,
            imageURLs: ["listing-29", "listing-30", "listing-31", "listing-32"],
            rating: 4.8,
            pricePerNight: 450,
            features: [.greatLocation, .greatForRemoteWork],
            amenities: [.wifi, .tv, .balcony],
            reviews: 100
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "Sarah Parker",
            ownerImageUrl: "profile-9",
            numberOfBedrooms: 6,
            numberOfBathrooms: 5,
            numberOfGuests: 12,
            numberOfBeds: 6,
            latitude: 48.8566,
            longitude: 2.3522,
            address: "606 Paris Ave",
            city: "Paris",
            state: "France",
            title: "Luxury Villa in Paris",
            type: .villa,
            imageURLs: ["listing-33", "listing-34", "listing-35", "listing-36"],
            rating: 5.0,
            pricePerNight: 2000,
            features: [.superHost, .top10PercentOfHomes],
            amenities: [.wifi, .alarmSystem, .pool],
            reviews: 250
        ),
        .init(
            id: NSUUID().uuidString,
            ownerUid: NSUUID().uuidString,
            ownerName: "David Brown",
            ownerImageUrl: "profile-10",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 4,
            numberOfBeds: 2,
            latitude: 35.6895,
            longitude: 139.6917,
            address: "707 Tokyo St",
            city: "Tokyo",
            state: "Japan",
            title: "Compact Apartment in Tokyo",
            type: .apartment,
            imageURLs: ["listing-37", "listing-38", "listing-39", "listing-40"],
            rating: 4.6,
            pricePerNight: 300,
            features: [.greatLocation, .greatCheckinExperience],
            amenities: [.wifi, .airConditioning, .microwave],
            reviews: 150
        )
    ]
}

